### ISSUE TITLE
Resolving 5432 port-conflict if having local Postgres and docker Postgres

### ISSUE THREAD

**Issue by Scandianis** [brayoh/recipe-app-react-prisma#1]
Modified docker-compose.yml for postgres service - added ports setting. Docker Postgres now accessible from pgAdmin (localhost:5442).

postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - "5442:5432"  
    volumes:
      - postgres:/var/lib/postgresql/data

**Comment by brayoh** [comment]
Resolved, thanks for pointing it out
